# Maintainer: yazgoo
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=baus-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="backed up ordering of standard input"
url="https://github.com/yazgoo/baus"
license=("MIT")
arch=("x86_64")
provides=("baus")
conflicts=("baus")
source=("https://github.com/yazgoo/baus/releases/download/v$pkgver/baus-$pkgver-x86_64.tar.gz")
sha256sums=("8c671dafa3045608724b36fcb4f97a382f20f3ad2045f712e4844b0466eeb5fb")

package() {
    install -Dm755 baus -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
